### ISSUE TITLE
Rosencrantz can't be used with threadpool

### ISSUE THREAD

**Issue by moigagoo** [andreaferretti/rosencrantz#8]
There's a compilation error as soon as you have both threadpool and Rosencrantz imported:

``` nim
import threadpool
import rosencrantz
```

``` shell
$ nim c --threads:on -r .\rosenthreads.nim
...
...\nim\0.14.2\lib\pure\asyncdispatch.nim(1288, 8) Error: 'cb' is not GC-safe as it accesses 'nameIterVar' which is a global using GC'ed memory
```

**Comment by andreaferretti** [comment]
I see. It seems that the problem is in the `dir` handler inside `staticsupport`. It already gives a warning when compiling normally, and it becomes an error with threads on. I am looking into this

**Comment by moigagoo** [comment]
@andreaferretti Wow! That was fast!

I just wanted to say that I absolutely adore Rosencrantz, thank you for it.

**Comment by andreaferretti** [comment]
:-)

**Comment by moigagoo** [comment]
@andreaferretti I see you replaced `toUpper` with `toUpperAscii`, so my code now crashes with `Error: undeclared field: 'toUpperAscii'`.

I assume I'm trying it too early? :-)

**Comment by andreaferretti** [comment]
Sorry, I was getting deprecation warnings because `toUpper` has been replaced with `toUpperAscii` on devel, and I thought I might fix those as well. I forgot that `toUpperAscii` is not even present on 0.14.2.

Maybe I should revert this change...

**Comment by moigagoo** [comment]
Maybe create a new branch "devel" which would correspond to Nim's devel, and revert the change in master?

This way, if I'm on Nim 0.14.2, I'll run `nimble install rosencrantz@#master`, and if I'm on Nim devel, I'll run `nimble install rosencrantz@#devel`.

**Comment by andreaferretti** [comment]
Done :-) I will fix the warnings when the next stable comes out.

Actually, I suggest avoiding `nimble install` for libraries. Just write a nimble file for your project and add rosencrantz as a dependency. This way, dependencies can be scoped for project. But that's just me

**Comment by moigagoo** [comment]
Thanks!

Sure, I'm including rosencrantz in my .nimble file :-) I just wanted to illustrate the proposed usage.

**Comment by moigagoo** [comment]
Sorry to bother you again, but I still can't make it work :-(

``` nim
import asyncdispatch, asynchttpserver
import threadpool
import rosencrantz

spawn waitFor newAsyncHttpServer().serve(Port 8080, ok("hello"))
sync()
```

``` shell
$ nim c -r --threads:on .\rt.nim
...
Hint: operation successful (37618 lines compiled; 2.875 sec total; 83.008MiB; Debug Build) [SuccessX]
My most dear lord!
Rosencrantz ready on port 8080
Traceback (most recent call last)
threadpool.nim(314)      slave
rt.nim(5)                waitForWrapper
asyncdispatch.nim(1681)  waitFor
asyncdispatch.nim(488)   poll
Error: unhandled exception: No handles or timers registered in dispatcher. [ValueError]
...
```

In the actual app I'm developing, the error is "Error: 'spawn' takes a GC safe call expression." There, I'm basically doing the same thing but spread among multiple modules. I've no clue :-(

**Comment by andreaferretti** [comment]
Well, this is a different matter. One thing is Rosencrantz not breaking when used together with threadpool, another one is actually serving on a different thread :-)

Sorry if it seems that I am nitpicking, but I think the latter can really be much more delicate. One issue is that file descriptors for sockets are stored in thread-local variables in the main thread (if I recall correctly). 

I have been looking into this when trying to see if I was able to actually make Rosencrantz multithreaded by performing the work of responding on the threadpool. I will at some revisit this, but probably after 1.0, when other people will look into how to handle multithreaded I/O.

It would help to know what you are trying to achieve exactly, so maybe I can try giving some advice

**Comment by moigagoo** [comment]
Thanks for the clarification :-)

What I'd like to achieve is to have a server listening for notifications and an API server listening for commands on a different port. The two may communicate via channels.

So my plan was just to launch the servers with `spawn`. I can do it this way with Jester, but I prefer Rosencrantz, so I'd rather use it.

**Comment by andreaferretti** [comment]
Just wanted to mention: still no idea what is going on, but it seems with latest Nim there are no errors anymore - rather, the server never responds
